Environment support implemented on the ReactJS Sample
jquant/jai-sdk.ts pull request #8
Opened 2022-06-20 15:57 UTC by felipegouveiae

2022-06-20 21:24 UTC, eljonathas requested changes

2022-06-20 21:24 UTC, eljonathas commented on src/collection-management/database-info/get-database-info.ts
> +    async getInfo(mode: mode = 'complete'): Promise<string[] | DatabaseInfo[]> {
Faltou tipar o `db_parents` como `string[]` em` DatabaseInfo`

![image](https://user-images.githubusercontent.com/7339257/174679354-a242ee54-c957-498e-bff6-93e15d4a8a12.png)

2022-06-20 21:27 UTC, eljonathas commented on src/collection-management/database-info/get-database-info.ts
> +    async getInfo(mode: mode = 'complete'): Promise<string[] | DatabaseInfo[]> {
Exemplo de retorno

![image](https://user-images.githubusercontent.com/7339257/174679728-6f583e88-a5dc-4ce2-9cba-0fab8afb2e82.png)

2022-06-20 21:54 UTC, izabelafonseca approved these changes
Changes approved.

2022-06-21 12:53 UTC, eljonathas approved these changes

2022-07-04 16:48 UTC, merged